url: https://blambert1080.github.io
baseurl: /church-website-agency-theme

# Site settings
title: Twin Creeks
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Byron McCollum
  pic: byron.png
  position: Elder
  social:
    - title: email
      url: #

- name: Don Lambert
  pic: don.png
  position: Elder
  social:
    - title: email
      url: #

- name: Ron Turnbow
  pic: ron.png
  position: Elder
  social:
    - title: email
      url: #

- name: Blake Lambert
  pic: blake.png
  position: Deacon
  social:
    - title: email
      url: #

- name: Cliff McCallister
  pic: cliff.png
  position: Deacon
  social:
    - title: email
      url: #

- name: Faron Travis
  pic: faron.png
  position: Deacon
  social:
    - title: email
      url: #

- name: Mark Cotter
  pic: mark.png
  position: Deacon
  social:
    - title: email
      url: #

- name: Mitch Himes
  pic: mitch.png
  position: Deacon
  social:
    - title: email
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: instagram 
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
